language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t raghukumarm/docker-react -f Dockerfile.dev .

script:
  # - docker run raghukumarm/docker-react npm run test -- --coverage
  - docker run -e CI=true raghukumarm/docker-react npm run test